apiVersion: apps/v1
kind: Deployment
metadata:
  name: bulletin
spec:
  replicas: 1
  selector:
    matchLabels:
        app: bulletin
  template:
    metadata:
      labels:
        app: bulletin
    spec:
      containers:
      - name: bulletin
        image: <containername>/bulletin:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 255m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          value: "bulletin"
---
apiVersion: v1
kind: Service
metadata:
  name: bulletin
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: bulletin